Version 2.1.1 (Digit triplet, GöSa, and parallel improvements)
Version 2.1.1 introduces new features and some bug-fixes:

The default corpus files to run FADE simulations for the Göttigen
Sentence test (and the Digit triplet test) have been added.
These were used to run the simulations for [1].
See also [2] for how to set up FADE for the Göttingen sentence test.

The previously added feature for convolving speech files with impulse
reponses during speech test corpus generation has been tested further
and seems to work as intended.

Corpus generation for speech tests can now be run in parallel.

The control over how many threads are used for computation can be set
for each task (e.g., features, training and recognition).
Therefore a new action was introduced: fade [PROJECT] parallel
This action has to be run on a project to enable multithreading.
The default value is 1 thread, because the optimal number greatly varies
from system to system and from task to task, and often using all cores
leads even to decreased in performance compared to using less threads.
A script to determine suitable numbers has been added
(examples/parallel_bench.sh).
To find suitable values for a specific task on your system:
1) create and fully configure a project with is representative
2) run the bench_parallel.sh script to test each task with the given
numbers of threads, e.g.
> bench_parallel.sh [YOURPROJECT] 4 6 8 12 16
The script will return the best parameters for each action on your
system.
You can write these values to the new fade.d/parallel.cfg file,
then "fade [PROJECT] parallel" will use these values.
Please have in mind that, for projects with different characteristics,
e.g., number of feature dimensions or number of simulated SNRs, the
optimal values can be different.

[1] https://www.vde-verlag.de/proceedings-en/454767060.html
[2]
https://github.com/m-r-s/fade/wiki/How-to-label-and-scaling-speech-files

diff --git a/fade.d/features b/fade.d/features
--- a/fade.d/features
+++ b/fade.d/features
@@ -1,7 +1,7 @@
 #!/bin/bash
 #USAGE      features [FEATURES] [FEATURES_ARGUMENT1] [FEATURES_ARGUMENT2] ...
 #TASK       run the feature extraction
-#COPYRIGHT  (C) 2014-2016 Marc René Schädler
+#COPYRIGHT  (C) 2014-2018 Marc René Schädler
 
 # Get the directory this script is stored in and its name
 DIR=$(cd "$( dirname "$0" )" && pwd)
@@ -82,8 +82,8 @@ fi
 
 # Check that feature extraction script exists
 if [ ! -f "${MFS}" ]; then
-    echo "feature extracton script '${MFS}' missing"
-    exit 1
+  echo "feature extracton script '${MFS}' missing"
+  exit 1
 fi
 
 # Prepare filelists if source directory exists
@@ -122,12 +122,14 @@ echo "create target directories"
 mkdirlist "${FCD}/targetlist"
 
 # Default to one block
-[ -z "$PARALLEL" ] && PARALLEL=1
+if [ -z "$PARALLEL_FEATURES" ]; then
+  PARALLEL_FEATURES=1
+fi
 
-# Perform feature extraction in $PARALLEL blocks
-echo "perform parallel feature extraction in $PARALLEL blocks"
-for ((I=1;$I<$[${PARALLEL}+1];I++)); do
-  echo "feature_batch_extract('${FCD}/sourcelist', '${FCD}/targetlist', ${PARALLEL}, ${I} ${FEXARGS})" | run-matlab 'ascii-tools' 'features' "${MFD}" &
+# Perform feature extraction in $PARALLEL_FEATURES blocks
+echo "perform parallel feature extraction in ${PARALLEL_FEATURES} blocks"
+for ((I=1;$I<$[${PARALLEL_FEATURES}+1];I++)); do
+  echo "feature_batch_extract('${FCD}/sourcelist', '${FCD}/targetlist', ${PARALLEL_FEATURES}, ${I} ${FEXARGS})" | run-matlab 'ascii-tools' 'features' "${MFD}" &
 done
 
 # Wait for parallel threads to finish
